<?php
/**
 * Created by PhpStorm.
 * User: zengz
 * Date: 2017/12/14
 * Time: 11:40
 */

namespace Admin\Controller;


class HudongAdminController extends AdminController
{
    protected $redis;
    protected $column;
    protected $stage;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->column = $this->getStartColumn();
        $this->stage = $this->getStartStage();
    }

    /**
     * 连接redis
     */
    public function connectRedis()
    {
        $this->redis = new \Redis();
        $this->redis->pconnect(C("REDIS_HOST"), C("REDIS_PORT"));
        C("REDIS_AUTH") && $this->redis->auth(C("REDIS_AUTH"));
    }

    /**
     * 获取开启栏目信息
     */
    protected function getStartColumn()
    {
        //加入权限后获取方法
        //$column_id = get_login_column();
        //$where = array('column_id'=>$column_id);
        //诗词大会使用
        $where = array('column_status'=>1);
        $column = M('column')->where($where)->find();
        return $column;
    }

    /**
     * 获取开启期信息
     */
    protected function getStartStage()
    {
        if ($this->column) {
            $column_id = $this->column['column_id'];
            $where = array('column_id'=>$column_id,'stage_status'=>1);
            $stage = M('stage')->where($where)->find();
            return $stage;
        } else {
            return false;
        }
    }

}