<?php
/**
 * Created by PhpStorm.
 * User: zengz
 * Date: 2017/12/5
 * Time: 11:03
 */

namespace Admin\Controller;

use Think\Db;


class ModuleController extends AdminController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->assign('menuname', "模块管理");
    }

    public function index()
    {
        $modules = M('module')->order('id ASC')->select();

        if ($modules) {
            $this->assign('modules', $modules);
        }

        $this->display();
    }

    public function addEdit()
    {
        $module_id = I('module_id', false);

        if ($module_id) {
            $module = M('module')->where(array('id' => $module_id))->find();
            $this->assign('module', $module);
        }

        $this->assign('title', $module_id ? '编辑模块' : '注册模块');
        $this->display();
    }

    public function saveModule()
    {
        $module_id = I('module_id', false);
        $data = array(
            'module_name'   => I('module_name', false),
            'module_code'   => I('module_code', false),
            'operator_time' => time()
        );

        if (!$data['module_name']) {
            $this->ajaxReturn(array('status' => -1, 'msg' => '无有效模块名称'));
        } else if (!$data['module_code']) {
            $this->ajaxReturn(array('status' => -2, 'msg' => '无有效模块代码'));
        }

        if ($module_id) {
            $res = M('module')->where(array('id' => $module_id))->save($data);
        } else {
            $res = M('module')->add($data);
        }

        if ($res) {
            $this->ajaxReturn(array('status' => 1, 'msg' => '提交成功'));
        } else {
            $this->ajaxReturn(array('status' => 0, 'msg' => '提交失败'));
        }
    }

    public function deleteModule()
    {
        $module_id = I('module_id', false);
        if (!$module_id) {
            $this->ajaxReturn(array('status' => -1, 'msg' => '模块ID无效'));
        }

        $res = M('module')->where(array('id' => $module_id))->delete();

        if ($res) {
            $this->ajaxReturn(array('status' => 1, 'msg' => '删除成功'));
        } else {
            $this->ajaxReturn(array('status' => 0, 'msg' => '删除失败'));
        }
    }

    public function showModules()
    {
        $modules = M('module')->order('id ASC')->select();
        if ($modules) {
            $this->assign('modules', $modules);
        }
    }

    public function selectModule()
    {
        $module_code = I('module_code', false);
        $stage_id = I('stage_id', false);

        if (!$module_code) {
            $this->ajaxReturn(array('status' => -1, 'msg' => '无效的模块代码'));
        } else if (!$stage_id) {
            $this->ajaxReturn(array('status' => -1, 'msg' => '无效的期数ID'));
        }

        $db = 'wei_' . $module_code;
        $db_exist = Db::query("show tables like '{$db}'");

        if ($db_exist) {
            $modules = M($module_code)->where(array('stage_id' => $stage_id))->order('id ASC')->select();
            if ($modules) {
                $this->ajaxReturn(array('status' => 1, 'msg' => '获取成功', 'data' => $modules));
            } else {
                $this->ajaxReturn(array('status' => 0, 'msg' => '没有数据'));
            }
        } else {
            $this->ajaxReturn(array('status' => -2, 'msg' => '该模块不存在'));
        }
    }
}